line: kodo
limit: 3
streamers:
  /root/blive/Videos/27165570/*.mp4:
    copyright: 1
    source: your source web
    tid: 138
    cover: 
    title: your title
    desc_format_id: 0
    desc: your description
    dynamic: "your dynamic"
    tag: your video tag split by ,
    dtime: ~
